@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteIdCommandParser" as DeleteIdCommandParser LOGIC_COLOR
participant "d:DeleteIdCommand" as DeleteIdCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("del t/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("del t/1")
activate AddressBookParser

create DeleteIdCommandParser
AddressBookParser -> DeleteIdCommandParser
activate DeleteIdCommandParser

DeleteIdCommandParser --> AddressBookParser
deactivate DeleteIdCommandParser

AddressBookParser -> DeleteIdCommandParser : parse("t/1")
activate DeleteIdCommandParser

create DeleteIdCommand
DeleteIdCommandParser -> DeleteIdCommand : DeleteIdCommand("t/1")
activate DeleteIdCommand

DeleteIdCommand --> DeleteIdCommandParser : d
deactivate DeleteIdCommand

DeleteIdCommandParser --> AddressBookParser : d
deactivate DeleteIdCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteIdCommandParser -[hidden]-> AddressBookParser
destroy DeleteIdCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteIdCommand : execute()
activate DeleteIdCommand

DeleteIdCommand -> Model : deleteTask(taskToDelete)
activate Model

Model --> DeleteIdCommand
deactivate Model

create CommandResult
DeleteIdCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteIdCommand
deactivate CommandResult

DeleteIdCommand --> LogicManager : result
deactivate DeleteIdCommand

[<--LogicManager
deactivate LogicManager
@enduml
